apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tahini.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tahini.labels" . | nindent 4 }}
type: Opaque
stringData:
  TAHINI_ADMIN_USER: {{ .Values.auth.adminUser | quote }}
  TAHINI_ADMIN_PASS: {{ required "auth.adminPass is required" .Values.auth.adminPass | quote }}
  TAHINI_SESSION_SECRET: {{ .Values.auth.sessionSecret | quote }}
